//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.13 at 11:14:22 AM IST 
//


package mule.learning.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mule.learning.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mule.learning.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZzzResponse }
     * 
     */
    public ZzzResponse createZzzResponse() {
        return new ZzzResponse();
    }

    /**
     * Create an instance of {@link ZzzResponse.Results }
     * 
     */
    public ZzzResponse.Results createZzzResponseResults() {
        return new ZzzResponse.Results();
    }

    /**
     * Create an instance of {@link ZzzResponse.Results.Result }
     * 
     */
    public ZzzResponse.Results.Result createZzzResponseResultsResult() {
        return new ZzzResponse.Results.Result();
    }

}
